language: php

php:
  - 7.4

before_script:
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpcs -s . --standard=phpcs.xml
  - vendor/bin/phpmd . text phpmd.xml
  - vendor/bin/phpunit ./tests
